### ISSUE TITLE
Amiga games not working with latest Amiga vision

### ISSUE THREAD

**Issue by grey04** [mrchrisster/MiSTer_SAM#245]
When SAM loads an amiga game (using amigavision) it just show the screen "missing kickstarter".
I think that's because now Amiga  vision use the "Amiga" core in _computers (and all his files use that core).

Instead SAM use the minimig default core..(but still load the game in the games/Amiga folder) maybe that's the problem?
`declare -g amigacore="$(find /media/fat/_Computer/ -iname "*minimig*")"`

**Comment by mrchrisster** [comment]
Thanks for letting me know. I didn't know they changed that. I'll update and make necessary adjustments

**Comment by grey04** [comment]
Yes, I have the rom, and the Amiga core works fine..it's the minimig core (which should be used by sam) that it doesnt load, maybe you have some special configuration?
Could you test if you launch the minimig core it works?

**Comment by mrchrisster** [comment]
I just updated SAM, can you check? I realized my minimig cfg has the kickstart info so that's why it was working for me

**Comment by mrchrisster** [comment]
Sorry, just fixed a small mistake, should work now

**Comment by grey04** [comment]
I checked and it's still not working,
I suspect the condition is wrong
`		if [ ! -f "/media/fat/_Computer/Amiga.mgl" ]; then`

shouldn't be without '!' ?

**Comment by mrchrisster** [comment]
Yes, sorry. Can you confirm it works without `!`?

**Comment by mrchrisster** [comment]
Fixed now.
